# Generated by Django 3.0.4 on 2020-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
